apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: example-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular
  type: NodePort
status:
  loadBalancer: {}
